[workspace]
members = ["algos/*", "cli", "core"]

[workspace.dependencies]
core.path = "./core"

rabin-karp.path = "./algos/rabin-karp"
shift-and.path = "./algos/shift-and"

adler32 = "1"
clap = { version = "4", features = ["derive"] }
